### ISSUE TITLE
Submit the 100 Builders week 2 update

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#104]

**Comment by salieflewis** [comment]
What have you shipped this week?

**Comment by salieflewis** [comment]
Who are your ideal users (right now)?
_Define a very specific group of people you think would absolutely love to use your project right now. The more specific you are, the better._

**Comment by salieflewis** [comment]
How many ideal users have you talked to this week?

What have you learned from talking to these users?

**Comment by salieflewis** [comment]
> Who are your ideal users (right now)? _Define a very specific group of people you think would absolutely love to use your project right now. The more specific you are, the better._

An assumption I make about our ideal users are that they are people who already believe that storing information on Ethereum is valuable. I wonder to what degree River is capable of crafting that notion. Meaning, does the way we design River aid users in believing that more and more. Or on the other hand, are we crafting an experience that makes users who don't necessarily believe storing information on Ethereum is valuable, potentially start to acknowledge that.

**Comment by salieflewis** [comment]
> How many ideal users have you talked to this week?
> 
> What have you learned from talking to these users?

Now that I'm thinking about this more, @0xTranqui actually mentioned that he did share the rudimentary demo to a couple people on Wednesday. I wonder what we can summarize from that experience that could aid in answering this question.

**Comment by salieflewis** [comment]
> What have you shipped this week?

In our first pass at a working channel that we prepared for last week, we were still hardcoding some information that was being displayed in our interface. Now, at the end of this week we've configured the routing architecture for Channels on River, and are now successfully pulling in data dynamically based on url params in the browser.

We updated our GraphQL queries to support sorting, and fixed an array of Typescript issues across the codebase.

We've continued to harden our backend architecture.

We created the fundamentals of a design system, called Estuary. Previously we were reaching for shadcn for nearly all of our componentry. We've come to the conclusion that we need a more familiar and intuitive way to piece together interfaces. By creating more constraints in our design language, we're forcing ourselves to design components with simplicity and an intuitive user experience being at the forefront of our minds.

We also added some Solidity scripting into our protocol repository, allowing us to more easily create Channels with custom configurations.

**Comment by salieflewis** [comment]
> How many ideal users have you talked to this week?
> 
> What have you learned from talking to these users?

A user on River is anyone who participates in a channel. Participating a channel is constituted by, either creating your own channel, or adding content to an existing channel.

At the moment, the testnet environment of our product has constraints that prevent us from just sharing the link to a live deploy and receiving feedback. However we were able to demonstrate use of a key feature to a few ideal users in person.

**Comment by ioeylim** [comment]
**What have you shipped this week?**
This week we configured the routing architecture so that our channels now dynamically fetch data based on the URL parameters. We’ve updated our GraphQL queries to support sorting, and fixed an array of Typescript issues while also improving our overall backend structure. Additionally, we started creating our own design system called “Estuary” to implement a more purposeful and clear design language for our interface. We want to prioritize making our new interactions feel as effortless and natural as possible, and believe that “Estuary” will help us deliver this experience to our users. 

**Who are your ideal users (right now)?**
We believe that our ideal users are people who already believe that storing information on Ethereum is valuable. They are curious about how Ethereum enables a new network for information, and want to discover products that create more context for what it means to store something on the blockchain. 

**How many ideal users have you talked to this week?**
3 (just a random number)

**What have you learned from talking to these users?** 
- It feels just as important to focus on why the product is something that matters, and not just how it works. 
- A simple user interface definitely helps to reduce confusion, but it still needs a lot of product demo/marketing to set up initial user expectation/motivation. 
- etc.

**Comment by salieflewis** [comment]
This week we configured route segments for channels. Channel data is now being dynamically based on URL parameters. In addition, we’ve updated our GraphQL queries to support sorting, and fixed an array of Typescript issues across the codebase. We started creating our own design system called Estuary. We were feeling a bit constrained by the current design libraries we were reaching for and felt like creating something purpose built, from scratch would aid in establishing a clear design language for our interface.

Lastly, we've added a Solidity script into our protocol repository, allowing us to more easily create channels with custom configurations.

**Comment by salieflewis** [comment]
Our ideal users are active in the Ethereum ecosystem, either producing information, collecting it, or promoting both on behalf of creators. River users likely share the value that storing information on Ethereum is valuable.

**Comment by 0xTranqui** [comment]
> I wonder to what degree River is capable of crafting that notion.

this is one of the questions I am most intrigued in

**Comment by 0xTranqui** [comment]
> > How many ideal users have you talked to this week?
> > What have you learned from talking to these users?
> 
> Now that I'm thinking about this more, @0xTranqui actually mentioned that he did share the rudimentary demo to a couple people on Wednesday. I wonder what we can summarize from that experience that could aid in answering this question.

there was no direct feedback that stands out, but moreso thoughts that I had reflecting on the experience. the summary of those thoughts is that river only needs to do 3 things well:
- let ppl create channels
- let ppl add to those channels
- let ppl explore/discover channels

there are other things we prob want river to also do, like letting ppl create new 1155 tokens that can be listed on channels, and letting ppl collect things that are listing on channels. but feeling more confident that focusing our efforts to communicate what river does to those first 3 bullet points would be most effective

**Comment by 0xTranqui** [comment]
> A user on River is anyone who participates in a channel. Participating a channel is constituted by, either creating your own channel, or adding content to an existing channel.

what about people who use River to browse channels? I would consider these ppl users still. but i get what ur saying

**Comment by ioeylim** [comment]
**What have you shipped this week?**
- Configured route segments so that our channels now dynamically fetch data based on URL parameters. 
- Updated our GraphQL queries to support sorting, and fixed an array of Typescript issues across the codebase.
- Began working on our own design system called “Estuary” to create a more purposeful and clear design language for our interface. 
- Added a Solidity script into our protocol repository, allowing us to more easily create channels with custom configurations. 

**Who are your ideal users (right now)?**
Our ideal users are people who already believe that storing information on Ethereum is valuable. They are curious about how new products like River can enable new ways to connect information and create more context for what it means to store information on Ethereum. 

**What have you learned from talking to these users?**
While there weren't specific feedback that stood out to us, it gave us an opportunity to realize that River only needs to do 3 things well: Allow users to create channels, to add/remove content from those channels, and to discover/explore channels. While there are definitely more features that we will want to ship, focusing our efforts to those 3 points feels like the biggest priority.
