### ISSUE TITLE
Build out view pages

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#176]
- [x] Layout scaffolding
- [x] Configure routing

During the last build I believe we configured view pages to live downstream from channels, aka items are always contextualized inside of the channels that house them. Perhaps it makes sense to revisit the world where items have routes independent of channels. I wonder if there is a drawback to this if we end up wanting to implement vertical scrolling. I think there is a world where this works regardless because we're not forced to re-render the layouts given they're identical.

How does this relate to the ability for items to be shared across channels? Should the item entity be updated such that the Channel field is an array type rather than a singular Channel?

cc: @1ifeworld/core

**Comment by salieflewis** [comment]
In reference to the proposed routes above, you're not able to call dynamic segments the same thing in the same tree. So rather than `id` to denote items, I opted for `index`. I also removed the in-between identifier "items" cause I think it is a bit redundant. We can keep this in if items instead get their own routes, free from channels.

So the new proposed route is: river.ph/channels/[id]/[index]

Gist of a `View` page component: https://gist.github.com/salieflewis/d600dd120feaabb6e74244bdcf8fcd49 

I know the data fetching is not quite right, trying to get a better understanding of what the metadata tables look like.

**Comment by 0xTranqui** [comment]
responding this question with 2 different lenses: 1) ux 2) "best" protocol implementation

1) in regards to ux my answer is quite short. I think the logic of all things flowing through channels makes a lot of sense, and dont see what we would unlike ux wise from having to introduce the concept of "items" living on their own outside of channels -- regardless of how the underlying protocol/data structures actually work. already now, items already exist "on their own" (all items have a unique id), but we choose not to render items by their unique id, rather via their position inside a channel

2) in terms of what the better protocol implementation could be, after doing this [experiment](https://gist.github.com/0xTranqui/4d6a624dba72a58a4b6f0c0fe743f484) earlier today of ~ inverting ~ the data structure so that "channels are added to items" as opposed to "items being added to channels" (what we have currently). there are a few reasons, but I think the primary one is that the main feature of "addItemToChannel" which currently requires multiple messages to process (create item, add item to channel -- which is messy bc you cant know the item you are creating before the txn so we had to implement a "relative referncing" approach), could be replaced with a simpler "createItem" which would look very similar but allow for the createItem message to include an array of channelIds to be added to. UX wise everything could work exactly the same, but the protocol would feel a bit different conceptually, as the act of adding/removing/editing channels would take place thru the manipulation of items, with channels being a downstream concept that can be constructed based on the actions that occur with items. items could now be created WITHOUT specificying a channel id, meaning they wouldnt show up on the site standalone but COULD show up when added to channels via other items. i think this approach is worth exploring for the potential it has to simplify the data structures + crud process

**Comment by salieflewis** [comment]
Resolved #184
