### ISSUE TITLE
Connect the `UploadDialog` with the `createPublication` action

### ISSUE THREAD

**Issue by salieflewis** [1ifeworld/river#73]
- [x] Ensure that the way we're passing arguments to our server actions works

I'm curious if the first most rudimentary version of the `UploadDialog` should just be:

Upload local item, preview the name of it, store it to ipfs, create a publication, provide user feedback that the item was added, and then include a profile page where you can see items you've uploaded.

cc: @ioeylim @jawndiego @0xTranqui

**Comment by 0xTranqui** [comment]
one thing to add here is that there is currently NO concept of just uploading a publication by itself. all publications need to be added to channels, so while I actually am a fan of this being the way we can into everything, it would need to involve the process of adding the publication to an existing (or not yet existing but to be created in same flow) channel. one way we could simplify this is by creating a channel that us 4 have access to and can all add to. what you think @salieflewis

**Comment by salieflewis** [comment]
Ok this is great, and duly noted. So then maybe the issue develops to become. Creating a publication and adding it to an existing channel. Assuming that the complexity of creating a channel within the `UploadDialog` is actually larger than simply creating a new channel from within the `UploadDialog`. Thoughts?

cc: @0xTranqui

**Comment by 0xTranqui** [comment]
@salieflewis joey already speccd this out in the design because this came out. it jsut a matter of when picking what channel to add your item to, u can go into a simplified create channel flow. so yea its more complex but we actually needed to make it anyway, so this still makes sense. if we wanted to avoid implementing the new channel flow from within the uplaod flow, we could still just setup a channel at protocol level we have access to.
